id: I66227009
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:11:16+00:00'
last_modified: '2022-06-08T06:20:28.857683+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20591
  title: སྙན་ངག་སྤྱི་དོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    66AC:
      image_group_id: I8LS20593
      title: ''
      total_pages: 135
      order: 1
      base_file: 66AC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
