id: P006714
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20591
  title: སྙན་ངག་སྤྱི་དོན།
  author: ''
  volumes:
    713de94c7a4c47b4b61d188502cbd707:
      image_group_id: I8LS20593
      title: ''
      volume_number: 1
      total_pages: 135
      base_file: v001.txt
